### ISSUE TITLE
Dúvida - Músicas

### ISSUE THREAD

**Issue by lucasrmagalhaes** [UlissesJunior/MusicTape#2]
Músicas estão sendo carregadas de qual fonte? Bem legal o projeto.

**Comment by UlissesJunior** [comment]
Olá Lucas,
Depois que você faz a sua contribuição, você recebe um tipo de README no email.
Nesse Readme eu explico que você precisa fazer o download da música pelo <a href="https://spotify-downloader.com/">Spotify Downloader</a>, pelo que eu entendi, o site converte o link da música em uma pesquisa para o Youtube e te fornece a mesma música em 320kbps. Depois disso, a pessoa entra no <a href="https://online-audio-converter.com/pt/">Conversor Online</a> e converte a qualidade para 160kps (uma qualidade menor, porém gasta menos espaço).
Após o download e conversão, a pessoa faz o upload para o client e a música fica guardada no storage do banco de dados.

**Comment by lucasrmagalhaes** [comment]
TOP!
