### ISSUE TITLE
[Melhoria] Retirar meta keywords

### ISSUE THREAD

**Issue by gabrielsozinho** [UlissesJunior/MusicTape#4]
Atualmente, essas tags mais atrapalham do que ajudam no SEO, já que desde 2002 os mecanismos de busca veem isso como um imã de spam.

O próprio Google recomenda não usar essas tags, antigamente elas eram usadas em contextos não relacionados com o site, por causa disso ele passou a desconsiderar.

Se quiser ler mais sobre, o link de um artigo: [https://pt.semrush.com/blog/meta-keywords-vale-a-pena-usar/](https://pt.semrush.com/blog/meta-keywords-vale-a-pena-usar/)

**Comment by UlissesJunior** [comment]
Olá Gabriel,
Muito obrigado pela indicação de melhoria, realmente eu achei um pouco estranho quando eu fui procurar um pouco sobre a SEO e aparecia alguns vídeos de muitos anos atrás. Vou remover a meta keywords do meu arquivo.
