### ISSUE TITLE
Url personalizada para o site

### ISSUE THREAD

**Issue by gabrielsozinho** [UlissesJunior/MusicTape#5]
Primeiramente quero pedir desculpas, porque eu me intrometi aqui do nada e já fiz uma PR e outra Issue. Isso pode parecer um pouco agressivo, mas só quero ajudar. :smile_cat:

Mas a sugestão dessa Issue é deixar a URL do site mais simples. Aqui estão sugestões de domínios que podem ser conseguidos gratuitamente:
- musictape.ga
- musictape.ml
- musictape.tk
- musictape.cf
- musictape.gq

Eu fiz um post no TabNews ensinando como criar um domínio assim, se a sugestão for aceita e precisar de alguma ajuda, pode me chamar no Discord (Gabriel Sozinho#6231), ou no Instagram (@gsozinhos). Vai ser um prazer ajudar. :smile:

**Comment by UlissesJunior** [comment]
Olá novamente Gabriel,
Não se preocupe com isso, o que eu queria era exatamente despertar a vontade das pessoas de ajudar no projeto, em momento algum você foi intrometido. 😄
Fui ler o seu post sobre isso no <a href="https://www.tabnews.com.br/GabrielSozinho/como-criar-sites-com-hospedagem-e-dominio-personalizado-sem-pagar-nada">TabNews</a>, ele está bem completo!
Só me ficou uma dúvida, eu tenho que pagar por esses domínios depois de 1 ano de uso?

**Comment by gabrielsozinho** [comment]
> Só me ficou uma dúvida, eu tenho que pagar por esses domínios depois de 1 ano de uso?

Não, só tem que ficar atento ao prazo pra renovar, senão outra pessoa pode acabar pegando o domínio.

**Comment by UlissesJunior** [comment]
A ok!! Muito obrigado pela dica, vou correr atrás disso.
